modbus:
  id: modbus1

modbus_controller:
  - id: modbus_device
    ## the Modbus device addr
    address: 0x2
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    register_type: holding
    value_type: U_DWORD
    address: 0x0001
    name: Machine Id
  
  - platform: modbus_controller
    register_type: holding
    value_type: U_QWORD
    address: 0x0003
    name: Serial Number

  - platform: modbus_controller
    register_type: holding
    address: 0x000C
    name: Software Version

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Extraction Flow
    register_type: holding
    address: 0x0110
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Flow
    register_type: holding
    address: 0x0111
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Outdoor Temperature
    register_type: holding
    address: 0x015E
    unit_of_measurement: "°C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Extracted Air Temperature
    register_type: holding
    address: 0x015F
    unit_of_measurement: "°C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Filter Life Time
    register_type: holding
    address: 0x010B
    unit_of_measurement: "Month"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Flow Set Point
    register_type: holding
    address: 0x0111
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Pressure Set Point
    register_type: holding
    address: 0x0113
    unit_of_measurement: "Pa"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Speed Set Point
    register_type: holding
    address: 0x0115
    unit_of_measurement: "rpm"

  - platform: modbus_controller
    register_type: holding
    address: 0x011C
    name: U1
    unit_of_measurement: V

  - platform: modbus_controller
    register_type: holding
    address: 0x011D
    name: U2
    unit_of_measurement: V

  - platform: modbus_controller
    register_type: holding
    address: 0x0151
    name: Power Supply Voltage
    unit_of_measurement: V
    lambda: return x * 100;

  - platform: modbus_controller
    register_type: holding
    address: 0x0152
    name: 0-10V Input
    unit_of_measurement: V

  - platform: modbus_controller
    register_type: holding
    address: 0x0152
    name: 0-10V Input
    unit_of_measurement: V
    
  - platform: modbus_controller
    register_type: holding
    address: 0x0153
    name: Switch State

  - platform: modbus_controller
    register_type: holding
    address: 0x0158
    name: Installer HMI

  - platform: modbus_controller
    register_type: holding
    address: 0x015A
    name: Filter Usage
    unit_of_measurement: '%'

  - platform: modbus_controller
    register_type: holding
    address: 0x015B
    name: Time Since Last Reset
    unit_of_measurement: Hours

  - platform: modbus_controller
    register_type: holding
    address: 0x015C
    name: Bypass Position

  - platform: modbus_controller
    register_type: holding
    address: 0x015D
    name: Bypass Consumption
    unit_of_measurement: A

  - platform: modbus_controller
    register_type: holding
    address: 0x0180
    name: Error Code

select:
  - platform: modbus_controller
    name: Regulation Mode
    use_write_multiple: true
    address: 0x0100
    optionsmap:
      "Constant Flow": 0
      "Constant Pressure": 1
      "Constant Speed": 2

  - platform: modbus_controller
    name: Ventilation Preset
    use_write_multiple: true
    address: 0x0101
    optionsmap:
      "Holidays": 0
      "Daily": 1
      "Boost": 2
      "Guest Party": 3

  - platform: modbus_controller
    name: "Bypass Mode"
    use_write_multiple: true
    address: 0x0103
    optionsmap:
      "OFF": 0
      "Auto": 1
      "Winter": 2
      "Summer": 3
      "Open": 4

number:
  - platform: modbus_controller
    register_type: holding
    address: 0x0108
    name: Holiday Duration
    unit_of_measurement: Minutes
    step: 5
    lambda: return x * 5;
    write_lambda: return x / 5;
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0109
    name: Kitchen High Speed Duration
    unit_of_measurement: Minutes
    step: 5
    lambda: return x * 5;
    write_lambda: return x / 5;
    use_write_multiple: true
  
  - platform: modbus_controller
    register_type: holding
    address: 0x010A
    name: Boost Duration
    unit_of_measurement: Minutes
    step: 5
    lambda: return x * 5;
    write_lambda: return x / 5;
    use_write_multiple: true
    
  - platform: modbus_controller
    register_type: holding
    address: 0x0110
    name: Extraction Flow Set Point
    unit_of_measurement: m3/h
    use_write_multiple: true
    
  - platform: modbus_controller
    register_type: holding
    address: 0x0112
    name: Extraction Pressure Set Point
    unit_of_measurement: Pa
    use_write_multiple: true
    
  - platform: modbus_controller
    register_type: holding
    address: 0x0114
    name: Extraction Speed Set Point
    unit_of_measurement: rpm
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x011A
    name: Summer Confort Temperature
    unit_of_measurement: °C
    use_write_multiple: true