esphome:
  name: inspirair-attic
  friendly_name: Inspirair Attic

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
  - ssid: !secret ssid1
    password: !secret password1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inspirair-Attic"
    password: "4topRODFzlWf"

captive_portal:

uart:
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16

<<: !include inspirair.yaml