modbus:
  id: modbus1

modbus_controller:
  - id: modbus_device
    ## the Modbus device addr
    address: 0x2
    modbus_id: modbus1
    setup_priority: -10
    
interval:
  # Activate God mode periodically (needed to retrieve fan values)
  # Interval needed because it get deactivated automatically after a while
  - interval: 5min
    then:
      select.set:
        id: user_level
        option: "God"

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Extraction Flow
    register_type: holding
    address: 0x0164
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Flow
    register_type: holding
    address: 0x0165
    unit_of_measurement: "m3/h"
  
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Extraction Fan Speed
    register_type: holding
    address: 0x0162
    unit_of_measurement: "rpm"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Supply Fan Speed"
    register_type: holding
    address: 0x0163
    unit_of_measurement: "rpm"

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Input Air Temperature
    register_type: holding
    address: 0x015E
    unit_of_measurement: "째C"
    lambda: return x * 0.01;
    accuracy_decimals: 2
  
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Extracted Air Temperature
    register_type: holding
    address: 0x015F
    unit_of_measurement: "째C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Supply Air Temperature
    register_type: holding
    address: 0x0160
    unit_of_measurement: "째C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    id: output_air_temperature
    register_type: holding
    address: 0x0161
    unit_of_measurement: "째C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Air Pressure
    register_type: holding
    address: 0x0166
    unit_of_measurement: "Pa"
    lambda: return x * 0.1;
    accuracy_decimals: 2

select:
  - platform: modbus_controller
    id: user_level
    name: User Level
    use_write_multiple: true
    address: 0x0010
    optionsmap:
      "Noob": 0
      "Useless": 2345
      "Interesting": 12054
      "God": 34102
      "-": 65535

  - platform: modbus_controller
    name: Regulation Mode
    use_write_multiple: true
    address: 0x0100
    optionsmap:
      "Constant Flow": 0
      "Constant Pressure": 1
      "Constant Speed": 2

  - platform: modbus_controller
    name: Ventilation Preset
    use_write_multiple: true
    address: 0x0101
    optionsmap:
      "Absence": 0
      "Daily": 1
      "Boost": 2
      "Guest Party": 3
      "Max": 4

  - platform: modbus_controller
    name: "Bypass Mode"
    use_write_multiple: true
    address: 0x0103
    optionsmap:
      "Manual": 0
      "Auto": 1
    
text_sensor:
  - platform: modbus_controller
    register_type: holding
    address: 0x0175
    raw_encode: HEXBYTES
    name: Season
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 1: return std::string("Winter");
        case 2: return std::string("Summer");
        default: return std::string("Unknown");
      }
      return x;

switch:
  - platform: modbus_controller
    register_type: holding
    address: 0x01ED
    name: Radon Mode

number:
  - platform: modbus_controller
    register_type: holding
    address: 0x01EC
    name: Bypass Switch Temperature
    lambda: return x * 0.01;
    write_lambda: return x * 100;

  - platform: modbus_controller
    register_type: holding
    address: 0x0410
    name: Extraction Flow Setpoint - Absence
    icon: mdi:fan-speed-1
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0411
    name: Supply Flow Setpoint - Absence
    icon: mdi:fan-speed-1
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0412
    name: Extraction Flow Setpoint - Daily
    icon: mdi:fan-speed-2
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0413
    name: Supply Flow Setpoint - Daily
    icon: mdi:fan-speed-2
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0414
    name: Extraction Flow Setpoint - Boost
    icon: mdi:fan-plus
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0415
    name: Supply Flow Setpoint - Boost
    icon: mdi:fan-plus
    use_write_multiple: true
    
  - platform: modbus_controller
    register_type: holding
    address: 0x0416
    name: Extraction Flow Setpoint - Guest
    icon: mdi:fan-speed-3
    use_write_multiple: true

  - platform: modbus_controller
    register_type: holding
    address: 0x0417
    name: Supply Flow Setpoint - Guest
    icon: mdi:fan-speed-3
    use_write_multiple: true

# button:
#   - platform: modbus_controller
#     id: save
#     register_type: holding
#     address: 0x0014
#     value_type: U_WORD
#     use_write_multiple: true
#     write_lambda: |-
#       payload.push_back(22577);
#       return 0 ;